version: '3'
services:
  env:
    # imageはtenserflow-notebook:latestを用いる
    # pipで何か追加したいときにはdockerfileを書く必要アリ
    image: jupyter/tensorflow-notebook:latest
    user: root
    # ___下記の設定はとりあえず。よく読んで決める___
    environment:
      LANG: C.UTF-8
      #   NB_UID: 1000
      #   NB_GID: 100
      #   GRANT_SUDO: "yes"
    volumes:
     # jovyanって何 -> jupyter(木星)の住民,jovyanくん。
     # データ継承　どっかーの中とフォルダを共有するパスの指定。
      - "./work:/home/jovyan/work"
    expose:
      - 8001
    ports:
      - 8001:8001

